/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStreamProxyRouteImport } from './routes/api/stream/proxy'
import { Route as ApiStreamIdPlaylistDotm3u8RouteImport } from './routes/api/stream/$id/playlist[.]m3u8'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamProxyRoute = ApiStreamProxyRouteImport.update({
  id: '/api/stream/proxy',
  path: '/api/stream/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamIdPlaylistDotm3u8Route =
  ApiStreamIdPlaylistDotm3u8RouteImport.update({
    id: '/api/stream/$id/playlist.m3u8',
    path: '/api/stream/$id/playlist.m3u8',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/stream/proxy': typeof ApiStreamProxyRoute
  '/api/stream/$id/playlist.m3u8': typeof ApiStreamIdPlaylistDotm3u8Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/stream/proxy': typeof ApiStreamProxyRoute
  '/api/stream/$id/playlist.m3u8': typeof ApiStreamIdPlaylistDotm3u8Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/stream/proxy': typeof ApiStreamProxyRoute
  '/api/stream/$id/playlist.m3u8': typeof ApiStreamIdPlaylistDotm3u8Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/stream/proxy' | '/api/stream/$id/playlist.m3u8'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/stream/proxy' | '/api/stream/$id/playlist.m3u8'
  id: '__root__' | '/' | '/api/stream/proxy' | '/api/stream/$id/playlist.m3u8'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiStreamProxyRoute: typeof ApiStreamProxyRoute
  ApiStreamIdPlaylistDotm3u8Route: typeof ApiStreamIdPlaylistDotm3u8Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/proxy': {
      id: '/api/stream/proxy'
      path: '/api/stream/proxy'
      fullPath: '/api/stream/proxy'
      preLoaderRoute: typeof ApiStreamProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/$id/playlist.m3u8': {
      id: '/api/stream/$id/playlist.m3u8'
      path: '/api/stream/$id/playlist.m3u8'
      fullPath: '/api/stream/$id/playlist.m3u8'
      preLoaderRoute: typeof ApiStreamIdPlaylistDotm3u8RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiStreamProxyRoute: ApiStreamProxyRoute,
  ApiStreamIdPlaylistDotm3u8Route: ApiStreamIdPlaylistDotm3u8Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
